// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9NsLd6MLRmecLSwYwi-9t80bRKlUQGD0',
    appId: '1:963886785612:web:4c3a219f9282c0471fc0e9',
    messagingSenderId: '963886785612',
    projectId: 'e-commerce-16d4b',
    authDomain: 'e-commerce-16d4b.firebaseapp.com',
    storageBucket: 'e-commerce-16d4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYLDsO7LaKwcPJBcqQTtgUcRIhrJxemyw',
    appId: '1:963886785612:android:fe6e133310ded6df1fc0e9',
    messagingSenderId: '963886785612',
    projectId: 'e-commerce-16d4b',
    storageBucket: 'e-commerce-16d4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PmQLDDXQ3MebFBoTnFzz6o1XGBnM0GE',
    appId: '1:963886785612:ios:fad74aebfd7377b21fc0e9',
    messagingSenderId: '963886785612',
    projectId: 'e-commerce-16d4b',
    storageBucket: 'e-commerce-16d4b.appspot.com',
    androidClientId: '963886785612-cshcfkvuv0ceuk6pc5hqeg4j98lj77fd.apps.googleusercontent.com',
    iosClientId: '963886785612-hi6p5bdec1ggdjdfg072vp6pqhfu7qst.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelompok9TokoOnline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PmQLDDXQ3MebFBoTnFzz6o1XGBnM0GE',
    appId: '1:963886785612:ios:fad74aebfd7377b21fc0e9',
    messagingSenderId: '963886785612',
    projectId: 'e-commerce-16d4b',
    storageBucket: 'e-commerce-16d4b.appspot.com',
    androidClientId: '963886785612-cshcfkvuv0ceuk6pc5hqeg4j98lj77fd.apps.googleusercontent.com',
    iosClientId: '963886785612-hi6p5bdec1ggdjdfg072vp6pqhfu7qst.apps.googleusercontent.com',
    iosBundleId: 'com.example.kelompok9TokoOnline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9NsLd6MLRmecLSwYwi-9t80bRKlUQGD0',
    appId: '1:963886785612:web:fee3b91f54e7b27b1fc0e9',
    messagingSenderId: '963886785612',
    projectId: 'e-commerce-16d4b',
    authDomain: 'e-commerce-16d4b.firebaseapp.com',
    storageBucket: 'e-commerce-16d4b.appspot.com',
  );

}